### ISSUE TITLE
release the data?

### ISSUE THREAD

**Issue by XL2248** [chat-task/wmt-chat-task#1]
Hi, when to release this data and then start the chat translation task?

**Comment by chat-task** [comment]
Hello,

We are preparing the dev sets as we speak. The original plan was to release
them by tomorrow June 15th, as is mentioned in the website. But, it seems
that we will be a few days delayed on this.
We will advertise the task in the relevant channels as soon as we have the
data ready.


Best,
Amin

**Comment by chat-task** [comment]
As you probably have noticed we released the dev sets today. And the test sets will be released in a few weeks.
So, I am gonna close this issue.
